npm: Bundle machine descriptions with Javascript library
A recent commit made bindings.js depend on other files in its working
directory, but didn't update the package.json to also distribute those
files. This resulted in the following error when running blueprints:
```
Error: Cannot find module './googleDescriptions'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/kelda/tester/node_modules/@quilt/quilt/blueprint/bindings.js:12:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```